services:
  playground:
    tty: true
    restart: always
    working_dir: /workspace
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
      - playground-volume:/workspace/node_modules

volumes:
  playground-volume:
